#开发环境配置信息

#服务端口
server:
  port:
    eureka-port: 9011
    config-port: 9012
    gateway-port: 9013
    mall-port: 9014
    sso-port: 9015
    order-port: 9016
    product-port: 9017
    official-port: 9018
    bmanage-port: 9019
    app-port: 9020
  #数据裤配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springcloud_sell?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  #rabbitmq配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  # 集成redis
  redis:
    host: 127.0.0.1   #192.168.106.128
    port: 6379
    password: 123456
    database: 0
    timeout: 10
    poolMaxTotal: 1000
    poolMaxIdle: 500
    poolMaxWait: 500
